/* B-2 browser checks: the real createMapCanvas with boundaries.
 *
 *   cd tests/e2e && npm install && node contornos.mjs
 *
 * Self-contained: serves the repository root on a random local port (no app
 * server, no database, no network), opens contornos.html in Chromium and
 * drives it with REAL mouse input (page.mouse), not Leaflet fire('click').
 *
 *   CHROMIUM=/path/to/chrome   use that binary instead of the "chrome" channel
 *   CONTORNOS_EVIDENCIA=dir     save screenshots and a JSON summary there
 *   MAPA_BASE=<git commit>      baseline MapCanvas for the XY-equivalence check
 *                               (default 09452fd, the B-2 application baseline)
 *
 * Fixture: tests/js/fixtures/geometria/contornos.json (fictional; generated by
 * the accepted B-1 parser, provenance inside).
 */

import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const BASE = process.env.MAPA_BASE ?? '09452fd26d38319567dce28a89db100ea61c739a';
const EVIDENCIA = process.env.CONTORNOS_EVIDENCIA ?? null;
const TIPOS = { '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript',
                '.css': 'text/css', '.json': 'application/json', '.png': 'image/png' };

/* The baseline renderer, with its relative imports pointed at /web/. */
const mapaBase = execFileSync('git', ['show', `${BASE}:web/components/map/MapCanvas.js`],
                              { cwd: RAIZ, encoding: 'utf8' })
  .replaceAll('"../../lib/', '"/web/lib/')
  .replaceAll('"./basemaps.js"', '"/web/components/map/basemaps.js"');

const servidor = http.createServer(async (req, res) => {
  const ruta = decodeURIComponent(new URL(req.url, 'http://local').pathname);
  try {
    if (ruta === '/__base/MapCanvas.js') {
      res.writeHead(200, { 'Content-Type': 'text/javascript' });
      res.end(mapaBase);
      return;
    }
    const archivo = path.join(RAIZ, path.normalize(ruta));
    if (!archivo.startsWith(RAIZ)) throw new Error('outside root');
    const cuerpo = await readFile(archivo);
    res.writeHead(200, { 'Content-Type': TIPOS[path.extname(archivo)] ?? 'application/octet-stream' });
    res.end(cuerpo);
  } catch {
    res.writeHead(404);
    res.end();
  }
});
await new Promise((ok) => servidor.listen(0, '127.0.0.1', ok));
const URL_HARNESS = `http://127.0.0.1:${servidor.address().port}/tests/e2e/contornos.html`;

const browser = await chromium.launch(process.env.CHROMIUM
  ? { executablePath: process.env.CHROMIUM } : { channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1200, height: 640 } });
const erroresPagina = [];
page.on('pageerror', (e) => erroresPagina.push(e.message));

if (EVIDENCIA) mkdirSync(EVIDENCIA, { recursive: true });
const resumen = { navegador: browser.version(), base: BASE, pasos: [] };
const foto = async (nombre) => {
  if (EVIDENCIA) await page.screenshot({ path: path.join(EVIDENCIA, `${nombre}.png`) });
};

const DOBLE_MS = 280;                     // MapCanvas's double-activation window
const esperarSeleccion = () => page.waitForTimeout(DOBLE_MS + 120);
const h = (fn, arg) => page.evaluate(fn, arg);
const pos = (id) => h((i) => __harness.canvas.posicionDe(i), id);
const seleccionado = () => h(() => __harness.seleccionado);
const enLista = () => h(() => document.querySelector('#lista [aria-pressed="true"]')?.dataset.id ?? null);

let fallos = 0;
async function paso(nombre, cuerpo) {
  try {
    await cuerpo();
    resumen.pasos.push({ paso: nombre, ok: true });
    console.log(`  ok  ${nombre}`);
  } catch (error) {
    fallos += 1;
    resumen.pasos.push({ paso: nombre, ok: false, error: String(error.message ?? error) });
    console.log(`  FALLA  ${nombre}\n        ${String(error.message ?? error).split("\n").slice(0, 8).join(" ")}`);
    await foto(`falla-${nombre.replace(/\W+/g, '-')}`);
  }
}

/* Container pixel for a [lon, lat] position (map div is at the page origin). */
async function pixel(lon, lat) {
  return h(([a, b]) => { const p = __harness.punto(b, a); return { x: p.x, y: p.y }; }, [lon, lat]);
}

/* Alpha of the map's canvases at a container pixel (0 = nothing drawn).
 * Leaflet's canvas redraws on the next animation frame, so wait two first. */
async function alfaContorno(x, y) {
  await h(() => new Promise((ok) => requestAnimationFrame(() => requestAnimationFrame(ok))));
  return h(([px, py]) => {
    const canvases = [...document.querySelectorAll('#mapa .leaflet-overlay-pane canvas')];
    const mapa = document.getElementById('mapa').getBoundingClientRect();
    let alfa = 0;
    for (const c of canvases) {
      const r = c.getBoundingClientRect();
      const escala = c.width / r.width;
      const x0 = Math.round((px + mapa.left - r.left) * escala);
      const y0 = Math.round((py + mapa.top - r.top) * escala);
      if (x0 < 0 || y0 < 0 || x0 >= c.width || y0 >= c.height) continue;
      alfa = Math.max(alfa, c.getContext('2d').getImageData(x0, y0, 1, 1).data[3]);
    }
    return alfa;
  }, [x, y]);
}

/* Click a list button and wait until the map has finished moving to it. */
async function clicLista(id) {
  await h(() => {
    window.__movido = new Promise((ok) => {
      let hecho = false;
      const fin = () => { if (!hecho) { hecho = true; requestAnimationFrame(() => ok()); } };
      __harness.canvas.map.once('moveend', fin);
      setTimeout(fin, 1500);
    });
  });
  await page.click(`#lista button[data-id="${id}"]`);
  await h(() => window.__movido);
}

await page.goto(URL_HARNESS);
await page.waitForFunction(() => document.title === 'listo');
const FIX = await h(() => __harness.fixture);
const cuerpo = (gid) => FIX.cuerpos[gid];
console.log(`Chromium ${browser.version()} · ${URL_HARNESS}`);

await paso('cada fila se coloca según contorno, XY o ninguno', async () => {
  assert.equal(await h(() => __harness.colocados), 11);                  // all but t-ninguna
  const esperado = {
    't-simple': 'contorno', 't-hueco': 'contorno', 't-multiparte': 'contorno', 't-u': 'contorno',
    't-xy': 'punto', 't-ninguna': null, 't-discrepa': 'contorno', 't-reemplazo': 'contorno',
    't-sin-cuerpo': 'contorno', 't-no-utilizable': 'punto', 't-coincide-contorno': 'contorno',
    't-coincide-xy': 'punto',
  };
  for (const [id, tipo] of Object.entries(esperado)) {
    const p = await pos(id);
    assert.equal(p?.tipo ?? null, tipo, id);
  }
  await foto('01-vista-inicial');
});

await paso('el ajuste inicial cubre todas las partes y puntos', async () => {
  const caja = await h(() => __harness.canvas.map.getBounds().toBBoxString().split(',').map(Number));
  for (const t of FIX.filas) {
    if (t.geometria?.utilizable) {
      if (t.id === 't-no-utilizable') continue;
      const [w, s, e, n] = t.geometria.bbox;
      assert.ok(w >= caja[0] && s >= caja[1] && e <= caja[2] && n <= caja[3], t.id);
    }
  }
});

await paso('discrepancia: se dibuja el contorno, no el X/Y almacenado', async () => {
  const p = await pos('t-discrepa');
  const g = FIX.filas.find((t) => t.id === 't-discrepa').geometria.punto_interior.coordinates;
  const esperado = await pixel(g[0], g[1]);
  assert.ok(Math.abs(p.x - esperado.x) < 1 && Math.abs(p.y - esperado.y) < 1);
  assert.deepEqual(await h(() => __harness.filas.find((t) => t.id === 't-discrepa')
    && [__harness.filas.find((t) => t.id === 't-discrepa').lat,
        __harness.filas.find((t) => t.id === 't-discrepa').lon]), [20.70, -100.50]);
});

await paso('lista → selección: encuadra el contorno multiparte entero y lo resalta', async () => {
  await clicLista('t-multiparte');
  assert.equal(await seleccionado(), 't-multiparte');
  const caja = await h(() => __harness.canvas.map.getBounds().toBBoxString().split(',').map(Number));
  const [w, s, e, n] = cuerpo('geo-multiparte').bbox;
  assert.ok(w >= caja[0] && s >= caja[1] && e <= caja[2] && n <= caja[3], 'whole extent');
  const p = await pos('t-multiparte');
  assert.equal(p.contorno, true, 'outline shown after framing');
  await foto('02-multiparte-seleccionado-desde-lista');
});

await paso('clic real en cada parte selecciona el mismo terreno', async () => {
  for (const parte of cuerpo('geo-multiparte').geojson.coordinates) {
    await h(() => { __harness.seleccionado = null; __harness.selecciones.length = 0; });
    const anillo = parte[0];
    const lon = (Math.min(...anillo.map((q) => q[0])) + Math.max(...anillo.map((q) => q[0]))) / 2;
    const lat = (Math.min(...anillo.map((q) => q[1])) + Math.max(...anillo.map((q) => q[1]))) / 2;
    const { x, y } = await pixel(lon, lat);
    await page.mouse.click(x, y);
    await esperarSeleccion();
    assert.deepEqual(await h(() => __harness.selecciones), ['t-multiparte']);
    assert.equal(await enLista(), 't-multiparte');
  }
});

await paso('hueco: sin relleno y sin selección al hacer clic dentro', async () => {
  await clicLista('t-hueco');
  assert.equal((await pos('t-hueco')).contorno, true);
  const [exterior, hueco] = cuerpo('geo-hueco').geojson.coordinates[0];
  const centro = (a) => [(Math.min(...a.map((q) => q[0])) + Math.max(...a.map((q) => q[0]))) / 2,
                         (Math.min(...a.map((q) => q[1])) + Math.max(...a.map((q) => q[1]))) / 2];
  const enHueco = await pixel(...centro(hueco));
  const [lonR, latR] = [exterior[0][0] + 0.0005, exterior[0][1] + 0.0005];
  const enRelleno = await pixel(lonR, latR);
  assert.equal(await alfaContorno(enHueco.x, enHueco.y), 0, 'hole is not filled');
  assert.ok(await alfaContorno(enRelleno.x, enRelleno.y) > 0, 'shell is filled');
  await h(() => { __harness.selecciones.length = 0; });
  await page.mouse.click(enHueco.x, enHueco.y);
  await esperarSeleccion();
  assert.deepEqual(await h(() => __harness.selecciones), [], 'a click in the hole selects nothing');
  await page.mouse.click(enRelleno.x, enRelleno.y);
  await esperarSeleccion();
  assert.deepEqual(await h(() => __harness.selecciones), ['t-hueco']);
  await foto('03-hueco-seleccionado');
});

/* Resolve once Leaflet has finished moving (fitBounds/setView may animate). */
const quieto = (accion) => h((codigo) => new Promise((ok) => {
  const mapa = __harness.canvas.map;
  let hecho = false;
  const fin = () => { if (!hecho) { hecho = true; requestAnimationFrame(() => ok()); } };
  mapa.once('moveend', fin);
  new Function(codigo)();
  setTimeout(fin, 1500);                  // no move at all: nothing to wait for
}), accion);

await paso('marca XY heredada: clic real la selecciona', async () => {
  await quieto('__harness.canvas.fitTo(__harness.filas)');
  const p = await pos('t-xy');
  await h(() => { __harness.selecciones.length = 0; });
  await page.mouse.click(p.x, p.y);
  await esperarSeleccion();
  assert.deepEqual(await h(() => __harness.selecciones), ['t-xy']);
  await foto('04-xy-seleccionado');
});

await paso('zoom lejano: símbolos en el punto interior; coincidentes como anillos', async () => {
  await h(() => __harness.canvas.setView([20.605, -100.39], 9));
  await page.waitForTimeout(200);
  for (const id of ['t-simple', 't-hueco', 't-multiparte', 't-u']) {
    assert.equal((await pos(id)).contorno, false, id);
  }
  const a = await pos('t-coincide-contorno');
  const b = await pos('t-coincide-xy');
  assert.ok(Math.abs(a.x - b.x) < 1 && Math.abs(a.y - b.y) < 1, 'same point');
  const escala = await h(() => __harness.escalas.at(-1));
  assert.equal(escala.contornosAEscala, 0);
  assert.ok(escala.contornos >= 8);
  await foto('05-zoom-lejano-simbolos');
});

await paso('doble clic en contorno: zoomToScale encuadra y reporta a_escala', async () => {
  await h(() => __harness.canvas.setView([20.6015, -100.398], 12));
  await page.waitForTimeout(200);
  const p = await pos('t-simple');
  await h(() => { __harness.dobles.length = 0; });
  await page.mouse.dblclick(p.x, p.y);
  await page.waitForTimeout(400);
  const [doble] = await h(() => __harness.dobles);
  assert.equal(doble.id, 't-simple');
  assert.equal(doble.resultado.estado, 'a_escala');
  assert.equal(doble.resultado.contorno, true);
  assert.equal((await pos('t-simple')).contorno, true);
});

await paso('cuerpo no cargado: símbolo distinto, nunca contorno, aviso escapado', async () => {
  const r = await h(() => __harness.canvas.zoomToScale('t-sin-cuerpo'));
  assert.equal(r.estado, 'contorno_no_disponible');
  const p = await pos('t-sin-cuerpo');
  assert.equal(p.contorno, false);
  await page.mouse.move(p.x, p.y);
  await page.waitForTimeout(300);
  const tooltip = await h(() => {
    const t = document.querySelector('.leaflet-tooltip.mark-tooltip');
    return t ? { html: t.innerHTML, negritas: t.querySelectorAll('b').length } : null;
  });
  assert.ok(tooltip, 'tooltip shown');
  assert.equal(tooltip.negritas, 0, 'name is text, not HTML');
  assert.match(tooltip.html, /&lt;b&gt;Sin&lt;\/b&gt;/);
  assert.match(tooltip.html, /Contorno no disponible/);
  await foto('06-sin-cuerpo');
  await page.mouse.move(5, 5);
});

await paso('reemplazo fallido: se dibuja el contorno activo anterior, no el pendiente', async () => {
  await clicLista('t-reemplazo');
  assert.equal((await pos('t-reemplazo')).contorno, true);
  const [w, s, e, n] = cuerpo('geo-reemplazo-anterior').bbox;
  const dentro = await pixel((w + e) / 2, (s + n) / 2);
  assert.ok(await alfaContorno(dentro.x, dentro.y) > 0, 'old layout drawn');
  const [pw, ps, pe, pn] = cuerpo('geo-reemplazo-pendiente').bbox;
  await h(([b]) => __harness.canvas.map.fitBounds([[b[1], b[0]], [b[3], b[2]]]), [[pw, ps, pe, pn]]);
  await page.waitForTimeout(300);
  const pendiente = await pixel((pw + pe) / 2, (ps + pn) / 2);
  assert.equal(await alfaContorno(pendiente.x, pendiente.y), 0, 'pending body never drawn');
});

await paso('filtrar retira capas; las entradas sobrantes del mapa no se dibujan', async () => {
  await clicLista('t-hueco');
  const [exterior] = cuerpo('geo-hueco').geojson.coordinates[0];
  const enRelleno = await pixel(exterior[0][0] + 0.0005, exterior[0][1] + 0.0005);
  assert.ok(await alfaContorno(enRelleno.x, enRelleno.y) > 0);
  const n = await h(() => __harness.render(__harness.fixture.filas.filter((t) => t.id !== 't-hueco')));
  assert.equal(n, 10);
  assert.equal(await pos('t-hueco'), null);
  assert.equal(await alfaContorno(enRelleno.x, enRelleno.y), 0, 'layer removed though its body is still in the map');
  await foto('07-filtrado-sin-hueco');
});

await paso('un clic pendiente sobre un terreno filtrado no llega a seleccionarse', async () => {
  await h(() => { __harness.render(__harness.fixture.filas); __harness.selecciones.length = 0; });
  await clicLista('t-u');
  await h(() => { __harness.selecciones.length = 0; });
  const p = await pos('t-u');
  await page.mouse.click(p.x, p.y);
  await h(() => __harness.render(__harness.fixture.filas.filter((t) => t.id !== 't-u')));
  await esperarSeleccion();
  assert.deepEqual(await h(() => __harness.selecciones), [], 'no late onSelect for a removed terrain');
});

await paso('render([]) limpia todo: capas, selección y conteo', async () => {
  assert.equal(await h(() => __harness.render([])), 0);
  for (const t of FIX.filas) assert.equal(await pos(t.id), null);
  const escala = await h(() => __harness.escalas.at(-1));
  assert.equal(escala.total, 0);
  const n = await h(() => __harness.render(__harness.fixture.filas));
  assert.equal(n, 11);
});

await paso('entrada inválida no rompe el mapa ni inventa contornos', async () => {
  const r = await h(() => {
    const filas = [
      null, {}, 42,
      { id: 'roto-1', lat: 20.61, lon: -100.39, ubicado: true },           // legacy XY
      { id: 'roto-2', lat: '20.6', lon: '-100.39', geometria: null },      // strings: unplaced
      { id: 'roto-3', lat: 20.62, lon: -100.39,
        geometria: { id: 'g-x', utilizable: true, bbox: 'mal', punto_interior: null } },
      { id: 'roto-4', lat: null, lon: null, terreno: '<img src=x onerror=alert(1)>',
        geometria: { id: 'g-nan', archivo_version_id: 'v', utilizable: true,
                     bbox: [-100.4, 20.6, -100.39, 20.61],
                     punto_interior: { type: 'Point', coordinates: [-100.395, 20.605] } } },
    ];
    const mapa = new Map([['g-nan', { bbox: [-100.4, 20.6, -100.39, 20.61],
      geojson: { type: 'MultiPolygon', coordinates: [[[[NaN, 1], [2, 3], [4, 5], [NaN, 1]]]] } }]]);
    const n = __harness.canvas.render(filas, { colorFor: () => '#2a78d6', geometrias: mapa });
    return { n, p1: __harness.canvas.posicionDe('roto-1'), p2: __harness.canvas.posicionDe('roto-2'),
             p3: __harness.canvas.posicionDe('roto-3'), p4: __harness.canvas.posicionDe('roto-4'),
             imgs: document.querySelectorAll('#mapa img[src="x"]').length };
  });
  assert.equal(r.n, 3);
  assert.equal(r.p1.tipo, 'punto');
  assert.equal(r.p2, null);
  assert.equal(r.p3.tipo, 'punto', 'malformed descriptor falls back to valid X/Y');
  assert.equal(r.p4.tipo, 'contorno');
  assert.equal(r.p4.contorno, false, 'invalid body is the unavailable symbol, never an outline');
  assert.equal(r.imgs, 0);
  assert.deepEqual(erroresPagina, []);
  await h(() => __harness.render(__harness.fixture.filas));
});

await paso('solo XY: idéntico al renderizador de la base', async () => {
  const r = await h(async () => {
    const nuevo = await import('/web/components/map/MapCanvas.js');
    const base = await import('/__base/MapCanvas.js');
    const filas = [];
    for (let i = 0; i < 60; i += 1) {
      filas.push({ id: `xy-${i}`, terreno: `Ficticio ${i}`, lat: 20.55 + (i % 10) * 0.004,
                   lon: -100.45 + Math.floor(i / 10) * 0.006, superficie_m2: 2000 + i * 900,
                   ubicado: i % 13 !== 0, asking_m2: 100 + i });
    }
    filas.push({ ...filas[1], id: 'xy-doble' });              // coincident pair
    const correr = (mod) => {
      const div = document.createElement('div');
      div.style.cssText = 'position:absolute;left:0;top:700px;width:900px;height:600px';
      document.body.append(div);
      const escalas = [];
      const c = mod.createMapCanvas(div, { onScaleChange: (e) => escalas.push(e) });
      c.invalidate();
      c.fitTo(filas);
      const n = c.render(filas, { colorFor: (t) => (t.asking_m2 > 130 ? '#c2410c' : '#2a78d6') });
      c.select('xy-5');
      const vista = c.viewport();
      const zooms = filas.map((t) => c.zoomToScale(t.id));
      c.setView(vista.center, vista.zoom);
      c.render(filas, { colorFor: (t) => (t.asking_m2 > 130 ? '#c2410c' : '#2a78d6') });
      c.select('xy-5');
      const pixeles = [...div.querySelectorAll('canvas')].map((cv) => cv.toDataURL());
      div.remove();
      return { n, vista, zooms, escalas: escalas.map(({ aEscala, total, zoom }) => ({ aEscala, total, zoom })),
               pixeles };
    };
    return { base: correr(base), nuevo: correr(nuevo) };
  });
  assert.equal(r.nuevo.n, r.base.n);
  assert.deepEqual(r.nuevo.vista, r.base.vista);
  assert.deepEqual(r.nuevo.zooms, r.base.zooms);
  assert.deepEqual(r.nuevo.escalas, r.base.escalas);
  assert.equal(r.nuevo.pixeles.length, r.base.pixeles.length);
  assert.deepEqual(r.nuevo.pixeles, r.base.pixeles, 'same pixels');
});

await paso('sin errores de página', async () => {
  assert.deepEqual(erroresPagina, []);
  assert.deepEqual(await h(() => __harness.errores), []);
});

resumen.fallos = fallos;
if (EVIDENCIA) writeFileSync(path.join(EVIDENCIA, 'resumen.json'), JSON.stringify(resumen, null, 1));
await browser.close();
servidor.close();
console.log(fallos ? `\n${fallos} comprobación(es) fallaron.` : '\nTodas las comprobaciones pasaron.');
process.exit(fallos ? 1 : 0);
