"""The standalone KMZ parser (server/kmz.py) against fictional fixtures.

Every KML document here is invented (tests/fixtures/kmz/, regenerated by its
generar.py). Each is packaged into a KMZ in memory; nothing is extracted to
disk and no network is used.
"""

from __future__ import annotations

import io
import json
import math
import os
import random
import re
import socket
import struct
import tempfile
import unittest
import warnings
import zipfile
from pathlib import Path
from unittest import mock

from server import kmz

FIXTURES = Path(__file__).parent / "fixtures" / "kmz"
LON, LAT = -100.4, 20.6
CLAVES = {"estado", "error", "avisos", "ignorados", "candidatos", "seleccion", "geometria",
          "ubicacion"}


def empaquetar(miembros, compresion=zipfile.ZIP_DEFLATED):
    """A KMZ from (name, bytes) pairs, in order; duplicate names allowed."""
    buf = io.BytesIO()
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")          # zipfile warns on duplicate names
        with zipfile.ZipFile(buf, "w", compresion) as zf:
            for nombre, datos in miembros:
                zf.writestr(nombre, datos)
    return buf.getvalue()


def kml(nombre):
    return (FIXTURES / f"{nombre}.kml").read_bytes()


def kmz_de(nombre):
    return empaquetar([("doc.kml", kml(nombre))])


def procesar(nombre, seleccion=None):
    return kmz.procesar_kmz(kmz_de(nombre), seleccion)


def codigos(resultado):
    return [a["codigo"] for a in resultado["avisos"]]


def documento(cuerpo):
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<kml xmlns="http://www.opengis.net/kml/2.2"><Document>'
            f"{cuerpo}</Document></kml>").encode()


def poligono_texto(puntos):
    texto = " ".join(f"{x:.7f},{y:.7f}" for x, y in puntos)
    return (f"<Placemark><name>Ficticio</name><Polygon><outerBoundaryIs><LinearRing>"
            f"<coordinates>{texto}</coordinates></LinearRing></outerBoundaryIs></Polygon>"
            "</Placemark>")


def circulo(posiciones, radio=0.01):
    """A closed ring of exactly `posiciones` positions (the last repeats the first)."""
    n = posiciones - 1
    puntos = [(LON + radio * math.cos(2 * math.pi * k / n),
               LAT + radio * math.sin(2 * math.pi * k / n)) for k in range(n)]
    return [*puntos, puntos[0]]


def en_anillo(p, anillo):
    x, y = p
    dentro = False
    for (x1, y1), (x2, y2) in zip(anillo, anillo[1:]):
        if (y1 > y) != (y2 > y) and x < x1 + (y - y1) * (x2 - x1) / (y2 - y1):
            dentro = not dentro
    return dentro


class Forma(unittest.TestCase):
    """Every result has one shape and serializes to JSON."""

    def test_todas_las_fixtures_dan_un_resultado_completo(self):
        nombres = sorted(p.stem for p in FIXTURES.glob("*.kml"))
        self.assertGreaterEqual(len(nombres), 35)
        for nombre in nombres:
            with self.subTest(nombre):
                r = procesar(nombre)
                self.assertEqual(set(r), CLAVES)
                self.assertIn(r["estado"], (kmz.LISTO, kmz.REQUIERE_SELECCION, kmz.RECHAZADO))
                json.dumps(r)
                if r["estado"] == kmz.LISTO:
                    self.assertIsNone(r["error"])
                    self.assertIsNotNone(r["geometria"])
                else:
                    self.assertIsNone(r["geometria"])
                    self.assertIsNone(r["ubicacion"])
                for mensaje in [r["error"]] + r["avisos"]:
                    if mensaje:
                        self.assertRegex(mensaje["codigo"], r"^[A-Z_]+$")
                        self.assertTrue(mensaje["mensaje"].strip())

    def test_el_modulo_no_esta_conectado_a_la_aplicacion(self):
        raiz = Path(__file__).resolve().parent.parent
        for ruta in [*raiz.joinpath("server").rglob("*.py"), *raiz.joinpath("api").rglob("*.py")]:
            if ruta.name == "kmz.py":
                continue
            with self.subTest(str(ruta)):
                self.assertIsNone(re.search(r"\bkmz\b", ruta.read_text(encoding="utf-8")))


class Aceptados(unittest.TestCase):
    def test_poligono_simple(self):
        r = procesar("poligono_simple")
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertEqual(r["seleccion"], [0])
        g = r["geometria"]
        self.assertEqual(g["geojson"]["type"], "MultiPolygon")
        self.assertEqual((g["partes"], g["huecos"], g["vertices"]), (1, 0, 5))
        # GeoJSON positions are [longitude, latitude], exactly as in the file.
        self.assertEqual(g["geojson"]["coordinates"][0][0][0], [LON, LAT])
        self.assertEqual(g["bbox"], [LON, LAT, -100.396, 20.603])        # W, S, E, N
        # ~417 m x ~333 m: the hand calculation is ~139,100 m².
        self.assertAlmostEqual(g["area_aproximada_m2"], 139_100, delta=139_100 * 0.01)
        self.assertEqual(r["ubicacion"], {"dentro_de_mexico": True, "utilizable": True})
        self.assertEqual(r["avisos"], [])

    def test_el_resultado_no_trae_x_ni_y(self):
        texto = json.dumps(procesar("poligono_simple"))
        for clave in ('"lat"', '"lon"', '"x"', '"y"', '"X"', '"Y"'):
            self.assertNotIn(clave, texto)

    def test_punto_interior_es_un_punto_geojson_dentro_del_relleno(self):
        for nombre in ("poligono_simple", "poligono_con_hueco", "forma_u", "multiparte"):
            with self.subTest(nombre):
                g = procesar(nombre)["geometria"]
                self.assertEqual(g["punto_interior"]["type"], "Point")
                p = g["punto_interior"]["coordinates"]
                dentro = [en_anillo(p, parte[0]) and not any(en_anillo(p, h) for h in parte[1:])
                          for parte in g["geojson"]["coordinates"]]
                self.assertTrue(any(dentro), p)

    def test_forma_u_no_usa_el_centro_de_su_caja(self):
        g = procesar("forma_u")["geometria"]
        w, s, e, n = g["bbox"]
        centro = [(w + e) / 2, (s + n) / 2]
        exterior = g["geojson"]["coordinates"][0][0]
        self.assertFalse(en_anillo(centro, exterior))
        self.assertTrue(en_anillo(g["punto_interior"]["coordinates"], exterior))

    def test_hueco_se_conserva_y_resta_area(self):
        g = procesar("poligono_con_hueco")["geometria"]
        self.assertEqual(g["huecos"], 1)
        self.assertEqual(len(g["geojson"]["coordinates"][0]), 2)
        lleno = kmz.area_aproximada_m2([tuple(p) for p in g["geojson"]["coordinates"][0][0]])
        self.assertLess(g["area_aproximada_m2"], lleno)

    def test_multiparte_es_un_solo_terreno(self):
        r = procesar("multiparte")
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertEqual(len(r["candidatos"]), 1)
        self.assertEqual(r["geometria"]["partes"], 2)

    def test_contenido_que_no_es_contorno_se_ignora_con_aviso(self):
        r = procesar("mixto_contorno_caminos_punto")
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertEqual(r["ignorados"], {"LineString": 1, "Point": 1})
        self.assertIn("KML_CONTENIDO_IGNORADO", codigos(r))

    def test_altitud_se_descarta_con_aviso(self):
        r = procesar("altitud_3d")
        self.assertIn("KML_ALTITUD_DESCARTADA", codigos(r))
        for posicion in r["geometria"]["geojson"]["coordinates"][0][0]:
            self.assertEqual(len(posicion), 2)

    def test_kml_sin_espacio_de_nombres(self):
        self.assertEqual(procesar("sin_espacio_de_nombres")["estado"], kmz.LISTO)

    def test_no_repara_ni_reordena(self):
        # A repeated consecutive position is legal and is returned as written.
        g = procesar("punto_repetido_consecutivo")["geometria"]
        anillo = g["geojson"]["coordinates"][0][0]
        self.assertEqual(len(anillo), 6)
        self.assertEqual(anillo[1], anillo[2])
        # Winding is kept: this fixture is counter-clockwise, a hole clockwise or not.
        hueco = procesar("poligono_con_hueco")["geometria"]["geojson"]["coordinates"][0][1]
        fuente = re.findall(r"<innerBoundaryIs>.*?<coordinates>(.*?)</coordinates>",
                            kml("poligono_con_hueco").decode())[0]
        self.assertEqual(hueco, [[float(v) for v in t.split(",")] for t in fuente.split()])


class Geografia(unittest.TestCase):
    """Validity and geographic eligibility are separate results."""

    def test_valido_fuera_de_mexico_no_es_utilizable(self):
        r = procesar("fuera_de_mexico")
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertIsNotNone(r["geometria"])
        self.assertEqual(r["ubicacion"], {"dentro_de_mexico": False, "utilizable": False})
        self.assertIn("GEOMETRIA_FUERA_DE_MEXICO", codigos(r))
        # Nothing was "corrected" toward Mexico.
        self.assertAlmostEqual(r["geometria"]["bbox"][0], -3.7)

    def test_usa_la_misma_extension_que_x_y(self):
        from server import validation
        self.assertIs(kmz.MEXICO_LAT, validation.MEXICO_LAT)
        self.assertIs(kmz.MEXICO_LON, validation.MEXICO_LON)

    def test_orden_invertido_no_se_corrige(self):
        r = procesar("orden_invertido")
        self.assertEqual(r["estado"], kmz.RECHAZADO)
        self.assertEqual(r["error"]["codigo"], "KML_COORDENADAS_FUERA_DE_RANGO")


class Seleccion(unittest.TestCase):
    def test_varios_contornos_nunca_eligen_el_primero(self):
        r = procesar("ambiguo_tres_lotes")
        self.assertEqual(r["estado"], kmz.REQUIERE_SELECCION)
        self.assertIsNone(r["geometria"])
        self.assertIsNone(r["error"])
        self.assertEqual([c["nombre"] for c in r["candidatos"]], ["Lote A", "Lote B", "Lote C"])
        self.assertEqual(r["candidatos"][0]["carpeta"], ["Documento ficticio", "Lotes ficticios"])
        self.assertTrue(all(c["valido"] for c in r["candidatos"]))
        self.assertNotIn("geojson", json.dumps(r["candidatos"]))

    def test_eleccion_de_uno(self):
        r = procesar("ambiguo_tres_lotes", [1])
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertEqual(r["seleccion"], [1])
        self.assertEqual(r["geometria"]["partes"], 1)
        self.assertAlmostEqual(r["geometria"]["bbox"][0], LON + 0.0025)

    def test_eleccion_de_varios_es_un_terreno_multiparte(self):
        r = procesar("ambiguo_tres_lotes", (2, 0))
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertEqual(r["seleccion"], [2, 0])
        self.assertEqual(r["geometria"]["partes"], 2)

    def test_lotes_contiguos_pueden_unirse(self):
        r = procesar("lotes_contiguos", [0, 1])
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertEqual(r["geometria"]["partes"], 2)

    def test_lotes_encimados_o_copiados_no_se_unen(self):
        for nombre in ("lotes_encimados", "lotes_copia"):
            with self.subTest(nombre):
                r = procesar(nombre, [0, 1])
                self.assertEqual(r["estado"], kmz.REQUIERE_SELECCION)
                self.assertEqual(r["error"]["codigo"], "GEOMETRIA_PARTES_SUPERPUESTAS")
                self.assertIsNone(r["geometria"])
                self.assertEqual(procesar(nombre, [1])["estado"], kmz.LISTO)

    def test_candidato_invalido_se_describe_y_no_se_puede_elegir(self):
        r = procesar("lotes_uno_invalido")
        self.assertEqual(r["estado"], kmz.REQUIERE_SELECCION)
        self.assertEqual([c["valido"] for c in r["candidatos"]], [True, False])
        self.assertEqual(r["candidatos"][1]["error"]["codigo"], "GEOMETRIA_AUTOINTERSECCION")
        self.assertIsNone(r["candidatos"][1]["area_aproximada_m2"])
        r = procesar("lotes_uno_invalido", [1])
        self.assertEqual(r["error"]["codigo"], "SELECCION_CONTORNO_INVALIDO")
        self.assertIn("Lote Moño", r["error"]["mensaje"])
        self.assertEqual(procesar("lotes_uno_invalido", [0])["estado"], kmz.LISTO)

    def test_selecciones_invalidas_nunca_fallan(self):
        """Supervisor probes [0, 0] and [0.0], plus every other malformed shape."""
        malas = [[0, 0], [0.0], [True], [False, 1], ["0"], [None], [], [-1], [3], [0, 1, 2, 0],
                 [[0]], "0", "abc", 0, 1.0, {0}, {"0": 0}, b"\x00", [2 ** 70], [0, 1, 2, 3]]
        for seleccion in malas:
            with self.subTest(seleccion=seleccion):
                r = procesar("ambiguo_tres_lotes", seleccion)
                self.assertEqual(r["estado"], kmz.REQUIERE_SELECCION)
                self.assertEqual(r["error"]["codigo"], "SELECCION_INVALIDA")
                self.assertIsNone(r["geometria"])
                self.assertEqual(len(r["candidatos"]), 3)
                json.dumps(r)

    def test_seleccion_duplicada_no_duplica_el_area(self):
        una = procesar("poligono_simple", [0])
        doble = procesar("poligono_simple", [0, 0])
        self.assertEqual(una["estado"], kmz.LISTO)
        self.assertEqual(doble["estado"], kmz.REQUIERE_SELECCION)
        self.assertEqual(doble["error"]["codigo"], "SELECCION_INVALIDA")
        self.assertIsNone(doble["geometria"])

    def test_un_solo_candidato_con_seleccion_fuera_de_rango(self):
        r = procesar("poligono_simple", [1])
        self.assertEqual(r["estado"], kmz.REQUIERE_SELECCION)
        self.assertEqual(r["error"]["codigo"], "SELECCION_INVALIDA")

    def test_archivo_rechazado_ignora_la_seleccion(self):
        self.assertEqual(procesar("solo_puntos", [0])["estado"], kmz.RECHAZADO)


class FormasInvalidas(unittest.TestCase):
    CASOS = {
        # Supervisor probes.
        "cuatro_copias_mismo_punto": "GEOMETRIA_VERTICES_INSUFICIENTES",
        "monio_autointerseccion": "GEOMETRIA_AUTOINTERSECCION",
        # Further rules.
        "anillo_abierto": "GEOMETRIA_ANILLO_ABIERTO",
        "anillo_corto": "GEOMETRIA_VERTICES_INSUFICIENTES",
        "colineal_sin_area": "GEOMETRIA_AUTOINTERSECCION",
        "pico_de_retroceso": "GEOMETRIA_AUTOINTERSECCION",
        "hueco_fuera": "GEOMETRIA_HUECO_INVALIDO",
        "hueco_toca_borde": "GEOMETRIA_HUECO_INVALIDO",
        "hueco_cruza_borde": "GEOMETRIA_HUECO_INVALIDO",
        "huecos_anidados": "GEOMETRIA_HUECO_INVALIDO",
        "dos_bordes_exteriores": "KML_POLIGONO_INCOMPLETO",
        "multiparte_encimada": "GEOMETRIA_PARTES_SUPERPUESTAS",
    }

    def test_cada_forma_invalida_se_rechaza_sin_geometria(self):
        for nombre, codigo in self.CASOS.items():
            with self.subTest(nombre):
                r = procesar(nombre)
                self.assertEqual(r["estado"], kmz.RECHAZADO)
                self.assertEqual(r["error"]["codigo"], codigo)
                self.assertIsNone(r["geometria"])
                self.assertIsNone(r["ubicacion"])
                self.assertEqual([c["valido"] for c in r["candidatos"]], [False])
                self.assertIsNone(r["candidatos"][0]["area_aproximada_m2"])

    def test_varios_candidatos_todos_invalidos(self):
        malo = poligono_texto([(LON, LAT)] * 4)
        r = kmz.procesar_kmz(empaquetar([("doc.kml", documento(malo + malo))]))
        self.assertEqual(r["estado"], kmz.RECHAZADO)
        self.assertEqual(r["error"]["codigo"], "KML_SIN_CONTORNO_VALIDO")
        self.assertEqual(len(r["candidatos"]), 2)

    def test_sin_area_cuando_no_hay_cruce(self):
        # Zero area can only survive the crossing checks through a direct call.
        error = kmz.validar_poligonos([[[(0.0, 0.0), (1e-7, 0.0), (1e-7, 1e-7), (0.0, 0.0)]]])
        self.assertEqual(error.codigo, "GEOMETRIA_SIN_AREA")


class PartesQueSeTocan(unittest.TestCase):
    """Axis-aligned rectangles in units of 0.001°, so every predicate is exact."""

    @staticmethod
    def r(x0, y0, x1, y1):
        u = 0.001
        a, b, c, d = LON + x0 * u, LAT + y0 * u, LON + x1 * u, LAT + y1 * u
        return [(a, b), (c, b), (c, d), (a, d), (a, b)]

    def codigo(self, *poligonos):
        error = kmz.validar_poligonos(list(poligonos))
        return error.codigo if error else None

    def test_borde_compartido_completo_o_parcial(self):
        self.assertIsNone(self.codigo([self.r(0, 0, 2, 1)], [self.r(2, 0, 4, 1)]))
        self.assertIsNone(self.codigo([self.r(0, 0, 2, 1)], [self.r(1, 1, 3, 2)]))
        self.assertIsNone(self.codigo([self.r(0, 0, 2, 1)], [self.r(2, 1, 3, 2)]))  # a corner

    def test_encimados_que_solo_comparten_bordes_colineales(self):
        self.assertEqual(self.codigo([self.r(0, 0, 2, 1)], [self.r(1, 0, 3, 1)]),
                         "GEOMETRIA_PARTES_SUPERPUESTAS")
        self.assertEqual(self.codigo([self.r(0, 0, 2, 1)], [self.r(1.99, 0, 3, 1)]),
                         "GEOMETRIA_PARTES_SUPERPUESTAS")

    def test_contenido_tocando_el_borde(self):
        self.assertEqual(self.codigo([self.r(0, 0, 1, 1)], [self.r(0, 0, 2, 2)]),
                         "GEOMETRIA_PARTES_SUPERPUESTAS")

    def test_isla_dentro_de_un_hueco(self):
        con_hueco = [self.r(0, 0, 3, 3), self.r(1, 1, 2, 2)]
        self.assertIsNone(self.codigo(con_hueco, [self.r(1, 1, 2, 2)]))
        self.assertEqual(self.codigo(con_hueco, [self.r(1, 1, 2.5, 2)]),
                         "GEOMETRIA_PARTES_SUPERPUESTAS")


class SinContorno(unittest.TestCase):
    def test_archivos_sin_contorno_dicen_que_contienen(self):
        casos = {"solo_puntos": "Point", "solo_lineas": "LineString",
                 "enlace_de_red": "NetworkLink", "superposicion_de_imagen": "GroundOverlay"}
        for nombre, contenido in casos.items():
            with self.subTest(nombre):
                r = procesar(nombre)
                self.assertEqual(r["estado"], kmz.RECHAZADO)
                self.assertEqual(r["error"]["codigo"], "KML_SIN_CONTORNO")
                self.assertIn(contenido, r["error"]["mensaje"])
                self.assertEqual(r["ignorados"], {contenido: 1})

    def test_documento_vacio(self):
        r = procesar("documento_vacio")
        self.assertEqual(r["error"]["codigo"], "KML_SIN_CONTORNO")
        self.assertEqual(r["ignorados"], {})

    def test_nunca_usa_la_red(self):
        def prohibido(*_a, **_k):
            raise AssertionError("network access attempted")
        with mock.patch.object(socket.socket, "connect", prohibido), \
                mock.patch("urllib.request.urlopen", prohibido):
            for nombre in ("enlace_de_red", "superposicion_de_imagen", "entidad_externa"):
                procesar(nombre)
            r = procesar("enlace_de_red")
        self.assertIn("KML_ENLACE_EXTERNO", codigos(r))


class TextoMalformado(unittest.TestCase):
    CASOS = {
        "entidades_dtd": "KML_DTD_NO_PERMITIDA",
        "entidad_externa": "KML_DTD_NO_PERMITIDA",
        "xml_roto": "KML_XML_INVALIDO",
        "coordenada_con_espacio": "KML_COORDENADAS_INVALIDAS",
        "coordenada_con_guion_bajo": "KML_COORDENADAS_INVALIDAS",
        "coordenada_nan": "KML_COORDENADAS_INVALIDAS",
    }

    def test_cada_caso(self):
        for nombre, codigo in self.CASOS.items():
            with self.subTest(nombre):
                r = procesar(nombre)
                self.assertEqual(r["estado"], kmz.RECHAZADO)
                self.assertEqual(r["error"]["codigo"], codigo)

    def test_xml_truncado_en_cualquier_punto(self):
        texto = kml("poligono_con_hueco")
        for corte in range(1, len(texto) - 10, 37):
            with self.subTest(corte=corte):
                r = kmz.procesar_kmz(empaquetar([("doc.kml", texto[:corte])]))
                self.assertEqual(r["estado"], kmz.RECHAZADO)

    def test_codificacion_desconocida(self):
        texto = kml("poligono_simple").replace(b'encoding="UTF-8"', b'encoding="UTF-Y"')
        r = kmz.procesar_kmz(empaquetar([("doc.kml", texto)]))
        self.assertEqual(r["error"]["codigo"], "KML_CODIFICACION_NO_SOPORTADA")

    def test_codificacion_latin1_declarada(self):
        texto = kml("poligono_simple").decode().replace("UTF-8", "ISO-8859-1")
        texto = texto.replace("Predio Ficticio Uno", "Predio Ficticio Año")
        r = kmz.procesar_kmz(empaquetar([("doc.kml", texto.encode("latin-1"))]))
        self.assertEqual(r["candidatos"][0]["nombre"], "Predio Ficticio Año")

    def test_mutaciones_nunca_lanzan_excepciones(self):
        """Seeded byte mutations of the fixtures, the KML text and the package."""
        rng = random.Random(20261007)
        fuentes = sorted(FIXTURES.glob("*.kml"))
        for vuelta in range(600):
            texto = bytearray(rng.choice(fuentes).read_bytes())
            modo = vuelta % 3
            if modo == 0:
                for _ in range(rng.randint(1, 8)):
                    texto[rng.randrange(len(texto))] = rng.randrange(256)
            datos = bytearray(empaquetar([("doc.kml", bytes(texto))]))
            if modo == 1:
                for _ in range(rng.randint(1, 8)):
                    datos[rng.randrange(len(datos))] = rng.randrange(256)
            elif modo == 2:
                datos = datos[:rng.randrange(len(datos))]
            seleccion = rng.choice([None, [0], [0, 1], [1], [0.0], "x"])
            with self.subTest(vuelta=vuelta):
                r = kmz.procesar_kmz(bytes(datos), seleccion)
                self.assertEqual(set(r), CLAVES)
                json.dumps(r)

    def test_entidad_no_declarada(self):
        r = kmz.procesar_kmz(empaquetar([("doc.kml", documento("<name>&x;</name>"))]))
        self.assertEqual(r["error"]["codigo"], "KML_XML_INVALIDO")


class EstructuraKml(unittest.TestCase):
    ANILLO = " ".join(f"{x},{y}" for x, y in
                      [(LON, LAT), (LON + .001, LAT), (LON, LAT + .001), (LON, LAT)])

    def procesar(self, cuerpo):
        return kmz.procesar_kmz(empaquetar([("doc.kml", documento(cuerpo))]))

    def borde(self, etiqueta="outerBoundaryIs", anillos=1, listas=1):
        lista = f"<coordinates>{self.ANILLO}</coordinates>" * listas
        return f"<{etiqueta}>" + f"<LinearRing>{lista}</LinearRing>" * anillos + f"</{etiqueta}>"

    def test_poligono_fuera_de_placemark_se_ignora(self):
        r = self.procesar(f"<Polygon>{self.borde()}</Polygon>")
        self.assertEqual(r["error"]["codigo"], "KML_SIN_CONTORNO")
        self.assertEqual(r["ignorados"], {"Polygon": 1})

    def test_poligono_sin_borde_exterior(self):
        r = self.procesar(f"<Placemark><Polygon>{self.borde('innerBoundaryIs')}</Polygon>"
                          "</Placemark>")
        self.assertEqual(r["error"]["codigo"], "KML_POLIGONO_INCOMPLETO")

    def test_un_borde_con_dos_anillos_o_dos_listas(self):
        for cuerpo in (self.borde(anillos=2), self.borde(listas=2)):
            with self.subTest(cuerpo=cuerpo[:60]):
                r = self.procesar(f"<Placemark><Polygon>{cuerpo}</Polygon></Placemark>")
                self.assertEqual(r["error"]["codigo"], "KML_POLIGONO_INCOMPLETO")

    def test_placemark_anidado_no_crea_otro_candidato(self):
        interior = f"<Placemark><name>Interior</name><Polygon>{self.borde()}</Polygon></Placemark>"
        r = self.procesar(f"<Placemark><name>Exterior</name><Polygon>{self.borde()}</Polygon>"
                          f"{interior}</Placemark>")
        self.assertEqual([c["nombre"] for c in r["candidatos"]], ["Exterior"])
        self.assertEqual(r["candidatos"][0]["partes"], 1)
        self.assertEqual(r["ignorados"], {"Placemark anidado": 1})


class Paquete(unittest.TestCase):
    def rechazo(self, datos):
        r = kmz.procesar_kmz(datos)
        self.assertEqual(r["estado"], kmz.RECHAZADO)
        return r["error"]["codigo"]

    def test_no_es_zip(self):
        for datos in (b"", b"esto no es un zip ficticio", kml("poligono_simple")):
            with self.subTest(datos=datos[:10]):
                self.assertEqual(self.rechazo(datos), "KMZ_NO_ES_ZIP")

    def test_zip_truncado(self):
        datos = kmz_de("poligono_simple")
        for corte in (10, len(datos) // 2, len(datos) - 30, len(datos) - 1):
            with self.subTest(corte=corte):
                self.assertIn(self.rechazo(datos[:corte]), ("KMZ_DANADO", "KMZ_NO_ES_ZIP"))

    def test_zip_corrupto(self):
        datos = bytearray(kmz_de("poligono_simple"))
        inicio = 30 + len("doc.kml")                     # first byte of compressed data
        for k in range(inicio, inicio + 40):
            datos[k] ^= 0xFF
        self.assertEqual(self.rechazo(bytes(datos)), "KMZ_DANADO")

    def test_cifrado(self):
        datos = bytearray(kmz_de("poligono_simple"))
        # Set the "encrypted" flag in the local header and the central directory.
        datos[6] |= 0x1
        central = datos.rfind(b"PK\x01\x02")
        datos[central + 8] |= 0x1
        self.assertEqual(self.rechazo(bytes(datos)), "KMZ_CIFRADO")

    def test_compresion_no_soportada(self):
        for compresion in (zipfile.ZIP_BZIP2, zipfile.ZIP_LZMA):
            with self.subTest(compresion=compresion):
                datos = empaquetar([("doc.kml", kml("poligono_simple"))], compresion)
                self.assertEqual(self.rechazo(datos), "KMZ_COMPRESION_NO_SOPORTADA")

    def test_sin_compresion_es_valido(self):
        datos = empaquetar([("doc.kml", kml("poligono_simple"))], zipfile.ZIP_STORED)
        self.assertEqual(kmz.procesar_kmz(datos)["estado"], kmz.LISTO)

    def test_varios_kml_son_ambiguos_aunque_haya_doc_kml(self):
        simple = kml("poligono_simple")
        for miembros in ([("a.kml", simple), ("b.kml", simple)],
                         [("doc.kml", simple), ("files/otro.kml", simple)],
                         [("doc.kml", simple), ("doc.kml", simple)],
                         [("doc.kml", simple), ("DOC.KML", simple)]):
            with self.subTest([n for n, _ in miembros]):
                self.assertEqual(self.rechazo(empaquetar(miembros)), "KMZ_VARIOS_KML")

    def test_sin_kml(self):
        datos = empaquetar([("files/plano.png", b"\x89PNG ficticio")])
        self.assertEqual(self.rechazo(datos), "KMZ_SIN_KML")

    def test_un_kml_en_subcarpeta_y_recursos(self):
        datos = empaquetar([("files/plano.png", b"\x89PNG ficticio"),
                            ("capas/terreno.kml", kml("poligono_simple"))])
        r = kmz.procesar_kmz(datos)
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertIn("KMZ_ARCHIVOS_ADICIONALES", codigos(r))

    def test_rutas_peligrosas_no_se_extraen(self):
        with tempfile.TemporaryDirectory() as tmp:
            anterior = os.getcwd()
            os.chdir(tmp)
            try:
                datos = empaquetar([("../../fuera.kml", kml("poligono_simple")),
                                    ("/abs/imagen.png", b"x")])
                r = kmz.procesar_kmz(datos)
                self.assertEqual(os.listdir(tmp), [])
            finally:
                os.chdir(anterior)
        self.assertEqual(r["estado"], kmz.LISTO)

    def test_zip64_o_dividido_no_se_admite(self):
        datos = bytearray(kmz_de("poligono_simple"))
        fin = datos.rfind(b"PK\x05\x06")
        struct.pack_into("<HH", datos, fin + 8, 0xFFFF, 0xFFFF)
        self.assertEqual(self.rechazo(bytes(datos)), "KMZ_NO_SOPORTADO")
        datos = bytearray(kmz_de("poligono_simple"))
        struct.pack_into("<H", datos, fin + 4, 1)                 # disk number
        self.assertEqual(self.rechazo(bytes(datos)), "KMZ_NO_SOPORTADO")

    def test_directorio_que_excede_el_archivo(self):
        datos = bytearray(kmz_de("poligono_simple"))
        fin = datos.rfind(b"PK\x05\x06")
        struct.pack_into("<L", datos, fin + 12, 10 ** 6)          # central directory size
        self.assertEqual(self.rechazo(bytes(datos)), "KMZ_DANADO")


class Limites(unittest.TestCase):
    """Each limit at exactly its value (accepted) and one past it (refused)."""

    def test_bytes_del_kmz(self):
        datos = kmz_de("poligono_simple")
        with mock.patch.object(kmz, "MAX_KMZ_BYTES", len(datos)):
            self.assertEqual(kmz.procesar_kmz(datos)["estado"], kmz.LISTO)
        with mock.patch.object(kmz, "MAX_KMZ_BYTES", len(datos) - 1):
            self.assertEqual(kmz.procesar_kmz(datos)["error"]["codigo"], "KMZ_DEMASIADO_GRANDE")

    def test_bytes_del_kmz_real(self):
        datos = empaquetar([("doc.kml", kml("poligono_simple"))], zipfile.ZIP_STORED)
        datos += b"\0" * (kmz.MAX_KMZ_BYTES + 1 - len(datos))
        self.assertEqual(kmz.procesar_kmz(datos)["error"]["codigo"], "KMZ_DEMASIADO_GRANDE")

    def test_entradas_reales(self):
        simple = kml("poligono_simple")
        base = [("doc.kml", simple)]
        justas = base + [(f"files/{k}.txt", b"") for k in range(kmz.MAX_ENTRADAS - 1)]
        self.assertEqual(kmz.procesar_kmz(empaquetar(justas))["estado"], kmz.LISTO)
        demasiadas = justas + [("files/extra.txt", b"")]
        r = kmz.procesar_kmz(empaquetar(demasiadas))
        self.assertEqual(r["error"]["codigo"], "KMZ_DEMASIADAS_ENTRADAS")

    def test_bytes_del_kml(self):
        texto = kml("poligono_simple")
        datos = empaquetar([("doc.kml", texto)])
        with mock.patch.object(kmz, "MAX_KML_BYTES", len(texto)):
            self.assertEqual(kmz.procesar_kmz(datos)["estado"], kmz.LISTO)
        with mock.patch.object(kmz, "MAX_KML_BYTES", len(texto) - 1):
            self.assertEqual(kmz.procesar_kmz(datos)["error"]["codigo"], "KML_DEMASIADO_GRANDE")

    def test_bytes_del_kml_real_comprimido(self):
        # Highly compressible: tiny package, oversized document.
        texto = kml("poligono_simple")
        cuerpo = texto.replace(b"</Document>", b" " * (kmz.MAX_KML_BYTES + 1) + b"</Document>")
        datos = empaquetar([("doc.kml", cuerpo)])
        self.assertLess(len(datos), 100_000)
        self.assertEqual(kmz.procesar_kmz(datos)["error"]["codigo"], "KML_DEMASIADO_GRANDE")

    def test_profundidad_real(self):
        def anidado(carpetas):
            # kml, Document, Folder x n, Placemark, Polygon, outerBoundaryIs,
            # LinearRing, coordinates: depth n + 7.
            pts = " ".join(f"{x},{y}" for x, y in
                           [(LON, LAT), (LON + .001, LAT), (LON, LAT + .001), (LON, LAT)])
            cuerpo = (f"<Placemark><Polygon><outerBoundaryIs><LinearRing><coordinates>{pts}"
                      "</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark>")
            return documento("<Folder>" * carpetas + cuerpo + "</Folder>" * carpetas)
        justo = kmz.MAX_PROFUNDIDAD - 7
        r = kmz.procesar_kmz(empaquetar([("doc.kml", anidado(justo))]))
        self.assertEqual(r["estado"], kmz.LISTO)
        r = kmz.procesar_kmz(empaquetar([("doc.kml", anidado(justo + 1))]))
        self.assertEqual(r["error"]["codigo"], "KML_DEMASIADO_ANIDADO")

    def test_elementos(self):
        texto = kml("poligono_simple")
        elementos = len(re.findall(rb"<[A-Za-z]", texto))
        datos = empaquetar([("doc.kml", texto)])
        with mock.patch.object(kmz, "MAX_ELEMENTOS", elementos):
            self.assertEqual(kmz.procesar_kmz(datos)["estado"], kmz.LISTO)
        with mock.patch.object(kmz, "MAX_ELEMENTOS", elementos - 1):
            r = kmz.procesar_kmz(datos)
            self.assertEqual(r["error"]["codigo"], "KML_DEMASIADOS_ELEMENTOS")

    def test_candidatos_reales(self):
        def lotes(n):
            cuerpo = "".join(poligono_texto(
                [(LON + k * .002, LAT), (LON + k * .002 + .001, LAT),
                 (LON + k * .002, LAT + .001), (LON + k * .002, LAT)]) for k in range(n))
            return empaquetar([("doc.kml", documento(cuerpo))])
        r = kmz.procesar_kmz(lotes(kmz.MAX_CANDIDATOS))
        self.assertEqual(r["estado"], kmz.REQUIERE_SELECCION)
        self.assertEqual(len(r["candidatos"]), kmz.MAX_CANDIDATOS)
        r = kmz.procesar_kmz(lotes(kmz.MAX_CANDIDATOS + 1))
        self.assertEqual(r["error"]["codigo"], "KML_DEMASIADOS_CONTORNOS")

    def test_vertices_reales(self):
        justo = documento(poligono_texto(circulo(kmz.MAX_VERTICES)))
        r = kmz.procesar_kmz(empaquetar([("doc.kml", justo)]))
        self.assertEqual(r["estado"], kmz.LISTO)
        self.assertEqual(r["geometria"]["vertices"], kmz.MAX_VERTICES)
        demasiado = documento(poligono_texto(circulo(kmz.MAX_VERTICES + 1)))
        r = kmz.procesar_kmz(empaquetar([("doc.kml", demasiado)]))
        self.assertEqual(r["error"]["codigo"], "KML_DEMASIADOS_VERTICES")

    def test_vertices_se_cortan_mientras_se_leen(self):
        texto = documento(poligono_texto(circulo(5000)))
        llamadas = []
        original = kmz._LectorKml._posicion

        def contar(self, tupla):
            llamadas.append(1)
            return original(self, tupla)

        with mock.patch.object(kmz, "MAX_VERTICES", 100), \
                mock.patch.object(kmz._LectorKml, "_posicion", contar):
            r = kmz.procesar_kmz(empaquetar([("doc.kml", texto)]))
        self.assertEqual(r["error"]["codigo"], "KML_DEMASIADOS_VERTICES")
        self.assertEqual(len(llamadas), 100)

    def test_vertices_cuentan_en_todo_el_documento(self):
        cuerpo = documento(poligono_texto(circulo(60)) + poligono_texto(circulo(60, 0.02)))
        with mock.patch.object(kmz, "MAX_VERTICES", 119):
            r = kmz.procesar_kmz(empaquetar([("doc.kml", cuerpo)]))
        self.assertEqual(r["error"]["codigo"], "KML_DEMASIADOS_VERTICES")

    def test_longitud_de_una_coordenada(self):
        def con_token(longitud):
            lon = "-100.4"
            lon += "0" * (longitud - len(lon) - len(",20.6"))
            token = f"{lon},20.6"
            self.assertEqual(len(token), longitud)
            pts = f"{token} -100.399,20.6 -100.4,20.601 {token}"
            return empaquetar([("doc.kml", documento(
                "<Placemark><Polygon><outerBoundaryIs><LinearRing><coordinates>" + pts
                + "</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark>"))])
        self.assertEqual(kmz.procesar_kmz(con_token(kmz.MAX_TOKEN))["estado"], kmz.LISTO)
        r = kmz.procesar_kmz(con_token(kmz.MAX_TOKEN + 1))
        self.assertEqual(r["error"]["codigo"], "KML_COORDENADAS_INVALIDAS")

    def test_nombre_se_acota(self):
        nombre = "Predio " + "x" * 1000
        cuerpo = poligono_texto(circulo(10)).replace("<name>Ficticio</name>",
                                                     f"<name>{nombre}</name>")
        r = kmz.procesar_kmz(empaquetar([("doc.kml", documento(cuerpo))]))
        self.assertEqual(len(r["candidatos"][0]["nombre"]), kmz.MAX_NOMBRE)

    def test_presupuesto_de_validacion(self):
        # A comb whose long teeth overlap in longitude; with a tiny budget the
        # result is a controlled refusal, never an unchecked acceptance.
        dientes = 200
        puntos = [(LON, LAT)]
        for k in range(dientes):
            y = LAT + k * 0.0002
            puntos += [(LON + 0.05, y), (LON + 0.05, y + 0.0001), (LON + 0.0001, y + 0.0001),
                       (LON + 0.0001, y + 0.0002)]
        puntos += [(LON, LAT + dientes * 0.0002), (LON, LAT)]
        datos = empaquetar([("doc.kml", documento(poligono_texto(puntos)))])
        self.assertEqual(kmz.procesar_kmz(datos)["estado"], kmz.LISTO)
        with mock.patch.object(kmz, "_PARES_BASE", 0), \
                mock.patch.object(kmz, "_PARES_POR_SEGMENTO", 1):
            r = kmz.procesar_kmz(datos)
        self.assertEqual(r["error"]["codigo"], "GEOMETRIA_DEMASIADO_COMPLEJA")


if __name__ == "__main__":
    unittest.main()
