"""Postgres storage for the shared deployment; local installations keep SQLite.

Repository SQL uses SQLite's parameter syntax. This small adapter converts only
placeholders and generated ids; data remains in normal relational tables.
Each session commits atomically and a transaction lock serializes the small
workspace's edits, including read-then-write operations such as import dedupe.
"""

from __future__ import annotations

import json
import os
import re
from collections.abc import Iterator, Mapping
from contextlib import contextmanager
from typing import Any

# Dependency order: backup and seeding insert in this order, so a folder must
# exist before the bases and maps that reference it.
LEGACY_TABLES = ("carpeta", "base", "terreno", "incidencia", "mapa", "mapa_capa", "mapa_terreno",
                 "formato_importacion", "importacion")
# v8: accounts and inventory content. team_session and team_login_failure are
# operational and deliberately absent. Text UUID keys: never in ID_TABLES.
INVENTORY_TABLES = ("team_user", "inventory_terrain", "inventory_revision", "inventory_event",
                    "inventory_operation_result")
TABLES = LEGACY_TABLES + INVENTORY_TABLES
# uso_ia is operational metadata, not workspace content: not in backups, but
# its rows still need generated ids.
ID_TABLES = (set(LEGACY_TABLES) - {"mapa_capa"}) | {"uso_ia"}
LOCK_ID = 84202026
SCHEMA_VERSION_KEY = "schema_version"


def enabled() -> bool:
    return bool(os.environ.get("ARA_MAP_DATABASE_URL"))


class Row(dict[str, Any]):
    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


def row_factory(cursor: Any) -> Any:
    columns = [column.name for column in (cursor.description or [])]
    return lambda values: Row(zip(columns, values))


class Cursor:
    def __init__(self, cursor: Any, generated: bool = False) -> None:
        self.cursor = cursor
        self.rowcount = cursor.rowcount
        row = cursor.fetchone() if generated else None
        self.lastrowid = row[0] if row else None

    def fetchone(self) -> Any:
        return self.cursor.fetchone()

    def fetchall(self) -> Any:
        return self.cursor.fetchall()

    def __iter__(self) -> Iterator[Any]:
        return iter(self.cursor)


class Connection:
    def __init__(self, raw: Any) -> None:
        self.raw = raw

    def execute(self, statement: str, params: Any = None) -> Cursor:
        command = statement.strip().upper()
        # The request session owns the outer transaction. Existing import
        # handlers explicitly bracket their work; preserve that as a savepoint.
        if command in {"BEGIN", "COMMIT", "ROLLBACK"}:
            statement = {"BEGIN": "SAVEPOINT import_transaction",
                         "COMMIT": "RELEASE SAVEPOINT import_transaction",
                         "ROLLBACK": "ROLLBACK TO SAVEPOINT import_transaction"}[command]
        if isinstance(params, Mapping):
            statement = re.sub(r"(?<!:):([a-zA-Z_]\w*)", r"%(\1)s", statement)
        elif params is not None:
            statement = statement.replace("?", "%s")
        match = re.match(r"\s*INSERT\s+INTO\s+(\w+)", statement, re.I)
        generated = bool(match and match.group(1) in ID_TABLES and "RETURNING" not in statement.upper())
        if generated:
            statement = statement.rstrip().rstrip(";") + " RETURNING id"
        return Cursor(self.raw.execute(statement, params), generated)


@contextmanager
def session() -> Iterator[Connection]:
    import psycopg

    with psycopg.connect(os.environ["ARA_MAP_DATABASE_URL"], row_factory=row_factory,
                         connect_timeout=15) as raw:
        raw.execute("SET LOCAL statement_timeout = '60s'")
        raw.execute("SET LOCAL lock_timeout = '30s'")
        raw.execute("SELECT pg_advisory_xact_lock(hashtext(current_schema()), %s)", (LOCK_ID,))
        yield Connection(raw)


def _to_postgres(sql: str) -> str:
    sql = re.sub(r"--[^\n]*", "", sql)
    sql = sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    sql = re.sub(r"\bINTEGER PRIMARY KEY\b", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
    return re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)


def schema_sql() -> str:
    """A fresh workspace's DDL. Creates missing tables but never alters
    existing ones: upgrading a live workspace is ``migrate_sql``'s job."""
    from .db import SCHEMA

    return _to_postgres(SCHEMA) + """
CREATE TABLE IF NOT EXISTS pending_import (
  token TEXT PRIMARY KEY, payload TEXT NOT NULL, created DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pending_created ON pending_import(created);
CREATE TABLE IF NOT EXISTS workspace_backup (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created TIMESTAMPTZ NOT NULL DEFAULT now(), payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS workspace_metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
""" + BORRADOR_SQL + inventory_sql()


def inventory_sql() -> str:
    """The v8 tables, idempotently. The inventory/revision pointer cycle is
    created without its two foreign keys, which are then added once both
    tables exist (Postgres has no ADD CONSTRAINT IF NOT EXISTS)."""
    from .db import INVENTORY_SCHEMA

    sin_ciclo = re.sub(r",?\s*CONSTRAINT fk_inventory_\w+ FOREIGN KEY[^\n]*", "", INVENTORY_SCHEMA)
    restricciones = "".join(f"""
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '{nombre}'
                 AND conrelid = 'inventory_terrain'::regclass) THEN
    ALTER TABLE inventory_terrain ADD CONSTRAINT {nombre} FOREIGN KEY (id, {columna})
      REFERENCES inventory_revision(inventory_id, id) DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $$;""" for nombre, columna in (("fk_inventory_draft", "draft_revision_id"),
                                   ("fk_inventory_published", "published_revision_id")))
    from .db import LOGIN_CLIENT_INDEX

    # A v8 workspace made before the per-client throttle key gains the column.
    cliente = ("ALTER TABLE team_login_failure ADD COLUMN IF NOT EXISTS client TEXT NOT NULL"
               " DEFAULT '';\n" + LOGIN_CLIENT_INDEX)
    return _to_postgres(sin_ciclo) + restricciones + "\n" + cliente


# Import-assistant drafts: the parsed file and the choices made so far, kept
# between requests that may land on different cloud workers. Temporary --
# expired rows are deleted -- and deliberately not part of workspace backups.
BORRADOR_SQL = """
CREATE TABLE IF NOT EXISTS borrador_importacion (
  token TEXT PRIMARY KEY, rejilla TEXT NOT NULL, estado TEXT NOT NULL,
  revision INTEGER NOT NULL, creado DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_borrador_creado ON borrador_importacion(creado);
"""

# Tables added after the first cloud release, in dependency order.
NUEVAS_TABLAS = ("carpeta", "formato_importacion", "importacion", "uso_ia")


def _crear_tabla(schema: str, nombre: str) -> str:
    tabla = re.search(rf"CREATE TABLE IF NOT EXISTS {nombre} \(.*?\);", schema, re.S)
    assert tabla is not None, nombre
    indices = re.findall(rf"CREATE INDEX IF NOT EXISTS \w+ ON {nombre}\(.*?\);", schema)
    return _to_postgres(tabla.group(0) + "\n" + "\n".join(indices)) + "\n"


def migrate_sql() -> str:
    """Bring an existing shared workspace up to the current schema.

    ``CREATE TABLE IF NOT EXISTS`` leaves an old table's definition alone, so
    new columns need explicit ALTERs. Every statement is idempotent: running
    this twice, or on a fresh workspace, changes nothing the second time.
    """
    from .db import FOLDER_INDEXES, SCHEMA, SCHEMA_VERSION

    return ("".join(_crear_tabla(SCHEMA, t) for t in NUEVAS_TABLAS) + BORRADOR_SQL
            + inventory_sql() + """
ALTER TABLE base ADD COLUMN IF NOT EXISTS carpeta_id INTEGER REFERENCES carpeta(id) ON DELETE SET NULL;
ALTER TABLE mapa ADD COLUMN IF NOT EXISTS carpeta_id INTEGER REFERENCES carpeta(id) ON DELETE SET NULL;
ALTER TABLE terreno ADD COLUMN IF NOT EXISTS moneda TEXT CHECK (moneda IN ('USD', 'MXN'));
ALTER TABLE mapa_terreno ADD COLUMN IF NOT EXISTS moneda TEXT;
""" + FOLDER_INDEXES + f"""
CREATE TABLE IF NOT EXISTS workspace_metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
INSERT INTO workspace_metadata(key, value) VALUES ('{SCHEMA_VERSION_KEY}', '{SCHEMA_VERSION}')
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
""")


def migrate(conn: Connection) -> None:
    """Apply ``migrate_sql`` inside the caller's session, which already holds
    the workspace's advisory lock, so two upgrades cannot interleave."""
    conn.raw.execute(migrate_sql(), prepare=False)


def schema_version(conn: Connection) -> int | None:
    """The version recorded by the last upgrade, or None before the first."""
    exists = conn.execute("SELECT to_regclass('workspace_metadata') AS t").fetchone()
    if exists is None or exists["t"] is None:
        return None
    row = conn.execute("SELECT value FROM workspace_metadata WHERE key = ?",
                       (SCHEMA_VERSION_KEY,)).fetchone()
    return int(row["value"]) if row else None


def backup() -> None:
    with session() as conn:
        # Tables that do not exist yet (a backup taken just before the upgrade
        # that creates them) are left out rather than failing the backup.
        payload = {table: [dict(row) for row in conn.execute(f"SELECT * FROM {table}")]
                   for table in TABLES
                   if conn.execute("SELECT to_regclass(?) AS t", (table,)).fetchone()["t"]}
        conn.execute("INSERT INTO workspace_backup(payload) VALUES (?)",
                     (json.dumps(payload, ensure_ascii=False),))
        conn.execute("DELETE FROM workspace_backup WHERE id NOT IN "
                     "(SELECT id FROM workspace_backup ORDER BY id DESC LIMIT 10)")
