/* Tests for the boundary-first location helpers (web/lib/geometria.js).
 * Run with: node --test tests/js/geometria.test.mjs
 *
 * Fixtures are fictional: contornos.json was generated by the accepted B-1
 * parser (provenance inside the file); ejemplo-contrato.json is the shared
 * contract v1 example, copied verbatim from instruction commit 3bada9f.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const g = await import("../../web/lib/geometria.js");
const { coincidentRingOffsets } = await import("../../web/lib/geo.js");
const { estadoUbicacion } = await import("../../web/lib/inventario.js");

const leer = (nombre) => JSON.parse(
  readFileSync(new URL(`./fixtures/geometria/${nombre}`, import.meta.url), "utf8"));
const FIX = leer("contornos.json");
const EJEMPLO = leer("ejemplo-contrato.json");
const fila = (id) => structuredClone(FIX.filas.find((t) => t.id === id));
const cuerpos = () => new Map(Object.entries(structuredClone(FIX.cuerpos)));

/* ------------------------------------------------------------ ubicacionDe */

test("fixture provenance: generated by the accepted B-1 parser", () => {
  assert.equal(FIX._procedencia.parser_commit, "efc362818ba64618dbfc23556db8678cde525336");
  assert.match(FIX._procedencia.kmz_py_sha256, /^[0-9a-f]{64}$/);
});

test("boundary-only terrain is located with blank X/Y", () => {
  const t = fila("t-simple");
  assert.deepEqual(g.ubicacionDe(t), { modo: "geometria", ubicado: true, xy: "sin_dato" });
});

test("XY-only terrain keeps the existing validator's verdict", () => {
  const t = fila("t-xy");
  assert.deepEqual(g.ubicacionDe(t), { modo: "punto", ubicado: true, xy: "valida" });
  // Swapped X/Y is invalid exactly as estadoUbicacion says; nothing is corrected.
  assert.equal(estadoUbicacion(t.lon, t.lat), "invalida");
  assert.deepEqual(g.ubicacionDe({ lat: t.lon, lon: t.lat }),
    { modo: "ninguna", ubicado: false, xy: "invalida" });
});

test("neither boundary nor X/Y: unplaced", () => {
  assert.deepEqual(g.ubicacionDe(fila("t-ninguna")),
    { modo: "ninguna", ubicado: false, xy: "sin_dato" });
  assert.deepEqual(g.ubicacionDe(), { modo: "ninguna", ubicado: false, xy: "sin_dato" });
});

test("boundary and X/Y disagree: boundary wins, X/Y is read but never written", () => {
  const t = Object.freeze(fila("t-discrepa"));
  const u = g.ubicacionDe(t);
  assert.equal(u.modo, "geometria");
  assert.equal(u.xy, "valida");
  assert.equal(t.lat, 20.70);
  assert.equal(t.lon, -100.50);
});

test("unusable or malformed descriptors are no descriptor at all", () => {
  const base = fila("t-simple").geometria;
  const malos = [
    { ...base, utilizable: false },
    { ...base, utilizable: "true" },
    { ...base, id: "" },
    { ...base, id: 7 },
    { ...base, bbox: [base.bbox[2], base.bbox[1], base.bbox[0], base.bbox[3]] },  // W > E
    { ...base, bbox: [1, 2, 3] },
    { ...base, bbox: ["-100.4", 20.6, -100.39, 20.61] },
    { ...base, punto_interior: { type: "Point", coordinates: [20.6015, -100.398] } },  // swapped
    { ...base, punto_interior: { type: "Point", coordinates: [-100.5, 20.6015] } },    // outside bbox
    { ...base, punto_interior: { coordinates: [-100.398, 20.6015] } },
    { ...base, bbox: [NaN, 20.6, -100.39, 20.61] },
    "geo-simple", 42, [], null,
  ];
  for (const geometria of malos) {
    assert.equal(g.descriptorActivo(geometria), false, JSON.stringify(geometria));
    // With valid X/Y the terrain falls back to its marker; without, it is unplaced.
    assert.equal(g.ubicacionDe({ lat: 20.6, lon: -100.4, geometria }).modo, "punto");
    assert.equal(g.ubicacionDe({ lat: null, lon: null, geometria }).modo, "ninguna");
  }
  // The fixture's out-of-Mexico geometry arrives with utilizable: false.
  assert.equal(g.ubicacionDe(fila("t-no-utilizable")).modo, "punto");
});

test("legacy rows without a geometria key keep their caller's ubicado", () => {
  assert.equal(g.modoDeFila({ id: 1, lat: 20.6, lon: -100.4, ubicado: true }), "punto");
  assert.equal(g.modoDeFila({ id: 1, lat: 20.6, lon: -100.4, ubicado: false }), "ninguna");
  assert.equal(g.modoDeFila(null), "ninguna");
  assert.equal(g.modoDeFila(fila("t-hueco")), "geometria");
});

test("shared contract v1 example maps through the A adapter rule", () => {
  // A's adapter: t.geometria = registro.ubicacion.geometria ?? null, raw lat/lon kept.
  const r = EJEMPLO.record;
  const t = { id: r.id, lat: r.draft.lat, lon: r.draft.lon,
              geometria: r.ubicacion.geometria ?? null };
  const u = g.ubicacionDe(t);
  assert.equal(u.modo, r.ubicacion.modo);
  assert.equal(u.xy, r.ubicacion.xy);
  const cuerpo = g.cuerpoLeaflet(t.geometria, new Map(Object.entries(EJEMPLO.geometryBodiesById)));
  assert.equal(cuerpo.estado, "cargado");
  assert.equal(t.lat, null);                     // the interior point never becomes X/Y
});

/* ----------------------------------------------------------- cuerpoLeaflet */

test("bodies convert [lon, lat] to Leaflet [lat, lng] explicitly", () => {
  const t = fila("t-simple");
  const c = g.cuerpoLeaflet(t.geometria, cuerpos());
  assert.equal(c.estado, "cargado");
  const fuente = FIX.cuerpos["geo-simple"].geojson.coordinates[0][0][0];
  assert.deepEqual(c.partes[0][0][0], [fuente[1], fuente[0]]);
  assert.deepEqual(g.puntoLeaflet(t.geometria.punto_interior),
    [t.geometria.punto_interior.coordinates[1], t.geometria.punto_interior.coordinates[0]]);
  assert.deepEqual(g.limitesLeaflet([-100.4, 20.6, -100.396, 20.603]),
    [[20.6, -100.4], [20.603, -100.396]]);
});

test("holes and every part are kept", () => {
  const hueco = g.cuerpoLeaflet(fila("t-hueco").geometria, cuerpos());
  assert.equal(hueco.partes.length, 1);
  assert.equal(hueco.partes[0].length, 2);          // shell + hole
  const multi = g.cuerpoLeaflet(fila("t-multiparte").geometria, cuerpos());
  assert.equal(multi.partes.length, 2);
});

test("cajaMayor is the largest part's shell box, which drives the handover", () => {
  const multi = g.cuerpoLeaflet(fila("t-multiparte").geometria, cuerpos());
  const [parteA, parteB] = FIX.cuerpos["geo-multiparte"].geojson.coordinates;
  const caja = (anillo) => [Math.min(...anillo.map((p) => p[0])), Math.min(...anillo.map((p) => p[1])),
                            Math.max(...anillo.map((p) => p[0])), Math.max(...anillo.map((p) => p[1]))];
  const [a, b] = [caja(parteA[0]), caja(parteB[0])];
  const mayor = (a[2] - a[0]) * (a[3] - a[1]) >= (b[2] - b[0]) * (b[3] - b[1]) ? a : b;
  assert.deepEqual(multi.cajaMayor, mayor);
  // Scattered tiny parts: the whole extent would hand over far earlier than
  // any single part can be hit.
  const total = fila("t-multiparte").geometria.bbox;
  assert.ok(g.zoomDeContorno(total, 20) <= g.zoomDeContorno(multi.cajaMayor, 20));
  // Holes never decide it.
  const hueco = g.cuerpoLeaflet(fila("t-hueco").geometria, cuerpos());
  assert.deepEqual(hueco.cajaMayor, fila("t-hueco").geometria.bbox);
});

test("missing body: no_disponible, never a fabricated outline", () => {
  const t = fila("t-sin-cuerpo");
  const sinEse = cuerpos();
  sinEse.delete("geo-sin-cuerpo");
  assert.deepEqual(g.cuerpoLeaflet(t.geometria, sinEse), { estado: "no_disponible" });
  assert.deepEqual(g.cuerpoLeaflet(t.geometria, null), { estado: "no_disponible" });
  assert.deepEqual(g.cuerpoLeaflet(t.geometria, { "geo-sin-cuerpo": {} }),
    { estado: "no_disponible" });                 // not a Map
});

test("failed replacement: the active descriptor's old body is used, never the pending one", () => {
  const t = fila("t-reemplazo");
  const mapa = cuerpos();
  assert.equal(t.geometria.id, "geo-reemplazo-anterior");
  const c = g.cuerpoLeaflet(t.geometria, mapa);
  assert.equal(c.estado, "cargado");
  const esperado = FIX.cuerpos["geo-reemplazo-anterior"].geojson.coordinates[0][0][0];
  assert.deepEqual(c.partes[0][0][0], [esperado[1], esperado[0]]);
  // A body filed under the active ID whose bounds differ from the descriptor's is
  // refused. (A matching bbox alone would not prove it is the same version.)
  mapa.set("geo-reemplazo-anterior", FIX.cuerpos["geo-reemplazo-pendiente"]);
  assert.equal(g.cuerpoLeaflet(t.geometria, mapa).estado, "invalido");
});

test("malformed bodies are invalid, never footprints", () => {
  const t = fila("t-simple");
  const bueno = FIX.cuerpos["geo-simple"];
  const con = (cambio) => new Map([["geo-simple", { ...structuredClone(bueno), ...cambio }]]);
  const anillo = bueno.geojson.coordinates[0][0];
  const casos = {
    tipo: con({ geojson: { type: "Polygon", coordinates: bueno.geojson.coordinates[0] } }),
    nan: con({ geojson: { type: "MultiPolygon",
                          coordinates: [[[[NaN, 20.6], ...anillo.slice(1)]]] } }),
    texto: con({ geojson: { type: "MultiPolygon",
                            coordinates: [[[["-100.4", "20.6"], ...anillo.slice(1)]]] } }),
    corto: con({ geojson: { type: "MultiPolygon", coordinates: [[anillo.slice(0, 3)]] } }),
    abierto: con({ geojson: { type: "MultiPolygon", coordinates: [[anillo.slice(0, -1)]] } }),
    vacio: con({ geojson: { type: "MultiPolygon", coordinates: [] } }),
    sinBbox: con({ bbox: null }),
    otraCaja: con({ bbox: [-100.5, 20.6, -100.396, 20.603] }),
    nulo: new Map([["geo-simple", "no es un cuerpo"]]),
  };
  for (const [nombre, mapa] of Object.entries(casos)) {
    assert.equal(g.cuerpoLeaflet(t.geometria, mapa).estado, "invalido", nombre);
  }
});

/* Review F1: coordinates must agree with the bounds they declare. */
const desplazar = (cuerpo, dLon, dLat = 0) => {
  const c = structuredClone(cuerpo);
  for (const poligono of c.geojson.coordinates) {
    for (const anillo of poligono) for (const p of anillo) { p[0] += dLon; p[1] += dLat; }
  }
  return c;
};
const conCuerpo = (id, cuerpo) => new Map([[id, cuerpo]]);

test("a body shifted away from its declared bounds is invalid, not drawn elsewhere", () => {
  const t = fila("t-simple");
  // The reviewer's reproducer: +2 degrees of longitude, metadata unchanged.
  const lejos = desplazar(FIX.cuerpos["geo-simple"], 2);
  assert.equal(g.cuerpoLeaflet(t.geometria, conCuerpo("geo-simple", lejos)).estado, "invalido");
  // Any shift beyond the tolerance, on either axis, is caught.
  for (const [dLon, dLat] of [[1e-6, 0], [0, -1e-6], [-0.0005, 0.0005]]) {
    const c = desplazar(FIX.cuerpos["geo-simple"], dLon, dLat);
    assert.equal(g.cuerpoLeaflet(t.geometria, conCuerpo("geo-simple", c)).estado, "invalido",
      `${dLon},${dLat}`);
  }
  // Last-digit rounding within the documented tolerance still loads.
  const casi = desplazar(FIX.cuerpos["geo-simple"], g.TOLERANCIA_GRADOS / 4);
  assert.equal(g.cuerpoLeaflet(t.geometria, conCuerpo("geo-simple", casi)).estado, "cargado");
});

test("collapsed or shrunken bodies are invalid", () => {
  const t = fila("t-simple");
  const bueno = FIX.cuerpos["geo-simple"];
  const p0 = bueno.geojson.coordinates[0][0][0];
  // Four identical points, original non-zero bbox kept (the reviewer's case).
  const punto = { ...structuredClone(bueno),
    geojson: { type: "MultiPolygon", coordinates: [[[[...p0], [...p0], [...p0], [...p0]]]] } };
  assert.equal(g.cuerpoLeaflet(t.geometria, conCuerpo("geo-simple", punto)).estado, "invalido");
  // A flat sliver along one edge, still inside the bbox.
  const [w, s, e] = bueno.bbox;
  const linea = { ...structuredClone(bueno),
    geojson: { type: "MultiPolygon", coordinates: [[[[w, s], [e, s], [w + (e - w) / 2, s], [w, s]]]] } };
  assert.equal(g.cuerpoLeaflet(t.geometria, conCuerpo("geo-simple", linea)).estado, "invalido");
  // A real square inside the bbox but not spanning it.
  const [, , , n] = bueno.bbox;
  const [mx, my] = [(w + e) / 2, (s + n) / 2];
  const chico = { ...structuredClone(bueno), geojson: { type: "MultiPolygon",
    coordinates: [[[[w, s], [mx, s], [mx, my], [w, my], [w, s]]]] } };
  assert.equal(g.cuerpoLeaflet(t.geometria, conCuerpo("geo-simple", chico)).estado, "invalido");
});

test("holes and other parts must stay inside the declared bounds too", () => {
  // A hole moved outside the bbox (the shell still spans it exactly).
  const tH = fila("t-hueco");
  const hueco = structuredClone(FIX.cuerpos["geo-hueco"]);
  for (const p of hueco.geojson.coordinates[0][1]) p[0] += 0.05;
  assert.equal(g.cuerpoLeaflet(tH.geometria, conCuerpo("geo-hueco", hueco)).estado, "invalido");
  // A collapsed hole.
  const plano = structuredClone(FIX.cuerpos["geo-hueco"]);
  const q = plano.geojson.coordinates[0][1][0];
  plano.geojson.coordinates[0][1] = [[...q], [...q], [...q], [...q]];
  assert.equal(g.cuerpoLeaflet(tH.geometria, conCuerpo("geo-hueco", plano)).estado, "invalido");
  // One part of a multipart moved away.
  const tM = fila("t-multiparte");
  const multi = structuredClone(FIX.cuerpos["geo-multiparte"]);
  for (const p of multi.geojson.coordinates[1][0]) p[0] += 0.5;
  assert.equal(g.cuerpoLeaflet(tM.geometria, conCuerpo("geo-multiparte", multi)).estado, "invalido");
});

test("every parser-produced fixture body is consistent and loads", () => {
  const mapa = cuerpos();
  for (const t of FIX.filas) {
    if (!g.descriptorActivo(t.geometria) || !mapa.has(t.geometria.id)) continue;
    assert.equal(g.cuerpoLeaflet(t.geometria, mapa).estado, "cargado", t.id);
  }
});

test("bodies past the parser's vertex limit are refused, not drawn", () => {
  const t = fila("t-simple");
  const n = g.MAX_POSICIONES_CUERPO + 1;
  const [w, s, e, nn] = t.geometria.bbox;
  const anillo = Array.from({ length: n - 1 }, (_, k) => [w + (e - w) * k / n, s]);
  anillo.push([...anillo[0]]);
  const mapa = new Map([["geo-simple", { ...FIX.cuerpos["geo-simple"],
    geojson: { type: "MultiPolygon", coordinates: [[anillo]] } }]]);
  assert.equal(g.cuerpoLeaflet(t.geometria, mapa).estado, "invalido");
  assert.ok(nn > s);
});

/* -------------------------------------------------------- scale and bounds */

test("handover: symbol at distant zoom, outline once the short side reaches 24 px", () => {
  const bbox = FIX.cuerpos["geo-simple"].bbox;    // ~417 m x ~333 m
  assert.equal(g.contornoAEscala(bbox, 8), false);
  const z = g.zoomDeContorno(bbox, 20);
  assert.equal(g.contornoAEscala(bbox, z), true);
  assert.equal(g.contornoAEscala(bbox, z - 1), false);
  const { alto } = g.tamanoEnPantalla(bbox, z);
  assert.ok(alto >= g.UMBRAL_CONTORNO_PX && alto < 2 * g.UMBRAL_CONTORNO_PX);
  assert.equal(g.UMBRAL_CONTORNO_PX, 24);
  assert.equal(g.zoomDeContorno([-100.4, 20.6, -100.4, 20.6000001], 20), null);
});

test("mixed bounds cover every boundary part and every XY point, nothing else", () => {
  const filas = FIX.filas;
  const [[s, w], [n, e]] = g.limitesDeFilas(filas);
  for (const t of filas) {
    const modo = g.modoDeFila(t);
    if (modo === "geometria") {
      const [bw, bs, be, bn] = t.geometria.bbox;
      assert.ok(bw >= w && be <= e && bs >= s && bn <= n, t.id);
    } else if (modo === "punto") {
      assert.ok(t.lat >= s && t.lat <= n && t.lon >= w && t.lon <= e, t.id);
    }
  }
  // The disagreeing terrain's X/Y is NOT in the bounds; its boundary is.
  const discrepa = filas.find((t) => t.id === "t-discrepa");
  const soloEse = g.limitesDeFilas([discrepa]);
  assert.deepEqual(soloEse, g.limitesLeaflet(discrepa.geometria.bbox));
  assert.equal(g.limitesDeFilas([fila("t-ninguna")]), null);
  assert.equal(g.limitesDeFilas([]), null);
});

test("coincident boundary symbol and XY mark get distinct rings", () => {
  const puntos = [fila("t-coincide-xy"), fila("t-coincide-contorno")].map(g.puntoDeSimbolo);
  assert.equal(puntos[0].lat, puntos[1].lat);
  assert.equal(puntos[0].lon, puntos[1].lon);
  const offsets = coincidentRingOffsets(puntos);
  assert.notEqual(offsets.get("t-coincide-xy"), offsets.get("t-coincide-contorno"));
  assert.equal(g.puntoDeSimbolo(fila("t-ninguna")), null);
});
